export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCTS_DETAIL_REQUEST = 'PRODUCTS_DETAIL_REQUEST'
export const PRODUCTS_DETAIL_SUCCESS = 'PRODUCTS_DETAIL_SUCCESS'
export const PRODUCTS_DETAIL_FAIL = 'PRODUCTS_DETAIL_FAIL'
