export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUECCSS = 'USER_LOGIN_SUECCSS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUECCSS = 'USER_REGISTER_SUECCSS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
